alerting:
  alertmanagers:
  -  static_configs:
      - targets: ['localhost:9093']

rule_files:
  - /etc/prometheus/rules.yml

scrape_configs:
  - job_name: 'prometheus'
    static_configs:
      - targets: ['localhost:9090']

  - job_name: 'udapeople'
    static_configs:
      - targets: ['ec2-54-242-197-245.compute-1.amazonaws.com:9100']
      