---
- name: "Update"
  become: true
  apt:
    update_cache: yes
    cache_valid_time: 86400

- name: "remove unneeded dependencies"
  become: true
  apt:
    autoremove: yes

- name: "upgrade packages"
  become: true
  apt:
    upgrade: yes

- name: "Install dependencies(nodejs and npm"
  become: true
  apt:
    name: ["nodejs", "npm"]
    state: latest
    update_cache: yes

- name: "Install npm2"
  become: true
  npm:
    name:  pm2
    global: yes
    production: yes
    state: present

- name: "Create Backend app directory"
  file:
    path: ~/backend_app_dir
    state: directory

- name: "Copy artifact into instance"
  become: true
  copy:
    src: ~/project/artifact.tar.gz
    dest: /home/ubuntu/backend_app_dir/artifact.tar.gz

- name: "Start application"
  become: true
  shell: |
    cd /home/ubuntu/backend_app_dir
    tar -xvzf artifact.tar.gz
    npm install
    npm run build
    pm2 stop all
    pm2 start npm -- start

